In [18]:
import pandas as pd

In [19]:
adams = pd.read_csv('../data/CFB_adams.csv')

In [20]:
adams.head()

,ELECTION,OFFICECD,RECIPID,CANCLASS,RECIPNAME,COMMITTEE,FILING,SCHEDULE,PAGENO,SEQUENCENO,...,INTEMPSTNM,INTEMPCITY,INTEMPST,INTOCCUPA,PURPOSECD,EXEMPTCD,ADJTYPECD,RR_IND,SEG_IND,INT_C_CODE
0,2025,1,1545,P,"Adams, Eric L",N,6,ABC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
1,2025,1,1545,P,"Adams, Eric L",N,7,ABC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
2,2025,1,1545,P,"Adams, Eric L",N,6,ABC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
3,2025,1,1545,P,"Adams, Eric L",N,6,ABC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN
4,2025,1,1545,P,"Adams, Eric L",N,6,ABC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,NaN

In [21]:
adams = adams[['RECIPNAME', 'DATE', 'REFUNDDATE', 'NAME', 'CITY', 'STATE', 'ZIP', 'OCCUPATION', 'EMPNAME', 'EMPSTRNO', 'EMPSTRNAME', 'EMPCITY', 'EMPSTATE', 'AMNT', 'MATCHAMNT']]

In [22]:
adams[adams.duplicated(['NAME'], keep=False)]

,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
119,"Adams, Eric L",8/23/2024,NaN,"Cooperstone, Elliot",East Hampton,NY,11937,Investor,InTandem Capital Partners,1,Vanderbilt Avenue,New York,NY,2100.0,0.0
120,"Adams, Eric L",8/23/2024,12/6/2024,"Cooperstone, Elliot",East Hampton,NY,11937,NaN,NaN,NaN,NaN,NaN,NaN,-2000.0,0.0
124,"Adams, Eric L",8/16/2024,NaN,"Curtis, Al",Staten Island,NY,10301,Consultant,A. Boima Curtis & Associates L,11,Tompkins Circle,Staten Island,NY,500.0,0.0
125,"Adams, Eric L",8/16/2024,9/4/2024,"Curtis, Al",Staten Island,NY,10301,NaN,NaN,NaN,NaN,NaN,NaN,-500.0,0.0
130,"Adams, Eric L",1/9/2025,NaN,"DeLusant, Steve",Hoboken,NJ,07030,President - Sales (NY),iHeartMedia Entertainment Inc,125,West 55th Street,New York,NY,250.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,"Adams, Eric L",1/10/2025,NaN,"Zamora, Pedro",East Elmhurst,NY,11369,Chief Executive Officer,1 Peza Inc,56-15,Northern Boulevard,Woodside,NY,2100.0,0.0
769,"Adams, Eric L",8/20/2024,NaN,"Zhang, Baoli",Staten Island,NY,10305,Day Care Center,Self,130-25,Blossom Ave,Flushing,NY,250.0,2.0
770,"Adams, Eric L",8/20/2024,12/6/2024,"Zhang, Baoli",Staten Island,NY,10305,NaN,NaN,NaN,NaN,NaN,NaN,-248.0,0.0
774,"Adams, Eric L",7/10/2024,NaN,"Zhao, Larry",Brooklyn,NY,11204,Manager,King Zone Realty,1521,70th Street,Brooklyn,NY,175.0,0.0
775,"Adams, Eric L",7/10/2024,12/6/2024,"Zhao, Larry",Brooklyn,NY,11204,NaN,NaN,NaN,NaN,NaN,NaN,-173.0,0.0

In [23]:
adams_clean = adams.drop_duplicates(subset="NAME")

In [30]:
adams_clean

,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
0,"Adams, Eric L",8/29/2024,NaN,"Abduganiev, Maksudjon",Brooklyn,NY,11229,Dispatcher,Dispatch Limo Seven Transporta,653,E 5th Street,Brooklyn,NY,250.0,250.0
1,"Adams, Eric L",1/8/2025,NaN,"Abrahimi, Farhad",Hicksville,NY,11801,Business,Self-Employed,9,West Marie Street,Hicksville,NY,500.0,0.0
2,"Adams, Eric L",8/11/2024,NaN,"Acevedo, Isaac",Staten Island,NY,10303,Not Employed,Not Employed,NaN,NaN,NaN,NaN,250.0,250.0
3,"Adams, Eric L",8/14/2024,NaN,"Acevedo, Melissa",Staten Island,NY,10303,RN,Richmond Univeristy Medical Ce,355,Bard Ave,Staten Island,NY,250.0,250.0
4,"Adams, Eric L",8/15/2024,NaN,"Achille, Carl",Alden Manor,NY,11003,Sergeant,New York City Police Departmen,8,Catherine Court,Alden Manor,NY,250.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,"Adams, Eric L",7/8/2024,NaN,"Zhuo, Xiao Wen",Staten Island,NY,10312,NaN,NaN,NaN,NaN,NaN,NaN,250.0,250.0
784,"Adams, Eric L",7/17/2024,NaN,"Zimmerman, Joseph",Brooklyn,NY,11221,Accountant,Ultimate Care,1000,Gates Avenue,Brooklyn,NY,250.0,250.0
785,"Adams, Eric L",1/9/2025,NaN,"Zirkiev, Shalom",Flushing,NY,11367,Real Estate,Self-Employed,141-24,Jewel Ave,Flushing,NY,2100.0,250.0
786,"Adams, Eric L",7/25/2024,NaN,"Zou, Raina",Bayside,NY,11360,Director of operations,Kevyn Aucoin,1209,Estates Lane,Queens,NY,250.0,250.0
787,"Adams, Eric L",1/7/2025,NaN,"Zupnick, Eliezer",Brooklyn,NY,11219,Broker,Zupnick Associates Insurance,1449,37th,Brooklyn,NY,500.0,0.0

In [31]:
adams_clean.to_csv('../output/adams_clean.csv')