In [2]:
import pandas as pd

In [4]:
myrie = pd.read_csv('../data/CFB_myrie.csv')

In [5]:
myrie = myrie[['RECIPNAME', 'DATE', 'REFUNDDATE', 'NAME', 'CITY', 'STATE', 'ZIP', 'OCCUPATION', 'EMPNAME', 'EMPSTRNO', 'EMPSTRNAME', 'EMPCITY', 'EMPSTATE', 'AMNT', 'MATCHAMNT']]

In [6]:
myrie[myrie.duplicated(['NAME'], keep=False)]

,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
0,"Myrie, Zellnor",12/6/2024,NaN,"Aaker, Julia",Brooklyn,NY,11238,Advertising,Leo Burnett,35,wacker,Chicago,IL,50.0,50.0
1,"Myrie, Zellnor",1/11/2025,NaN,"Aaker, Julia",Brooklyn,NY,11238,Advertising,Leo Burnett,35,wacker,Chicago,IL,50.0,50.0
4,"Myrie, Zellnor",7/21/2024,NaN,"Abate, Liam",Queens,NY,11104,Greenpoint Beer and Ale,Bartender,1150,Manhattan Avenue,Brooklyn,NY,10.0,10.0
5,"Myrie, Zellnor",8/21/2024,NaN,"Abate, Liam",Queens,NY,11104,Greenpoint Beer and Ale,Bartender,1150,Manhattan Avenue,Brooklyn,NY,10.0,10.0
6,"Myrie, Zellnor",8/31/2024,NaN,"Abate, Liam",Queens,NY,11104,Greenpoint Beer and Ale,Bartender,1150,Manhattan Avenue,Brooklyn,NY,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2815,"Myrie, Zellnor",1/11/2025,NaN,"Zeno, Mark",Manhattan,NY,10028,Attorney,Center for Appellate Litigatio,120,Wall Street,New York,NY,100.0,100.0
2819,"Myrie, Zellnor",12/13/2024,NaN,"Zolot, Barbara",New York,NY,10028,Attorney,Center for Appellate Litigatio,120,Wall Street,New York,NY,100.0,100.0
2820,"Myrie, Zellnor",1/11/2025,NaN,"Zolot, Barbara",New York,NY,10028,Attorney,Center for Appellate Litigatio,120,Wall Street,New York,NY,100.0,100.0
2823,"Myrie, Zellnor",9/14/2024,NaN,"Zulack, Mary",Brooklyn,NY,11201,Not Employed,Not Employed,166,Columbia Hts,Brooklyn,NY,50.0,50.0
2824,"Myrie, Zellnor",1/11/2025,NaN,"Zulack, Mary",Brooklyn,NY,11201,Not Employed,Not Employed,166,Columbia Hts,Brooklyn,NY,100.0,100.0

In [7]:
myrie_clean = myrie.drop_duplicates(subset="NAME")

In [9]:
myrie_clean.to_csv('../output/myrie_clean.csv')