In [13]:
import pandas as pd

In [26]:
adams = pd.read_csv('../output/adams_clean.csv')
lander = pd.read_csv('../output/lander_clean.csv')
ramos = pd.read_csv('../output/ramos_clean.csv')
myrie = pd.read_csv('../output/myrie_clean.csv')
mamdani = pd.read_csv('../output/mamdani_clean.csv')
stringer = pd.read_csv('../output/stringer_clean.csv')

In [27]:
all_clean = pd.concat([ adams, lander, mamdani, myrie, ramos, stringer ])
print(len(all_clean))

16028

In [28]:
all_clean

,Unnamed: 0,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
0,0,"Adams, Eric L",8/29/2024,NaN,"Abduganiev, Maksudjon",Brooklyn,NY,11229,Dispatcher,Dispatch Limo Seven Transporta,653,E 5th Street,Brooklyn,NY,250.0,250.0
1,1,"Adams, Eric L",1/8/2025,NaN,"Abrahimi, Farhad",Hicksville,NY,11801,Business,Self-Employed,9,West Marie Street,Hicksville,NY,500.0,0.0
2,2,"Adams, Eric L",8/11/2024,NaN,"Acevedo, Isaac",Staten Island,NY,10303,Not Employed,Not Employed,NaN,NaN,NaN,NaN,250.0,250.0
3,3,"Adams, Eric L",8/14/2024,NaN,"Acevedo, Melissa",Staten Island,NY,10303,RN,Richmond Univeristy Medical Ce,355,Bard Ave,Staten Island,NY,250.0,250.0
4,4,"Adams, Eric L",8/15/2024,NaN,"Achille, Carl",Alden Manor,NY,11003,Sergeant,New York City Police Departmen,8,Catherine Court,Alden Manor,NY,250.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140,3175,"Stringer, Scott M",9/8/2024,NaN,"Zou, Fenger",Flushing,NY,11362,Real Estate Agent,Fengz International INC,34-36,Union Street,Flushing,NY,250.0,250.0
2141,3176,"Stringer, Scott M",11/25/2024,NaN,"Zou, Min Fen",Brooklyn,NY,11214,Floor manager,Min Fen Zou,6812,15th Avenue,Brooklyn,NY,250.0,250.0
2142,3177,"Stringer, Scott M",10/7/2024,NaN,"Zrake, Donald",Levittown,NY,11756,Engineer,Hallam Engineering,97-37,63rd Dr.,Flushing,NY,75.0,0.0
2143,3178,"Stringer, Scott M",12/2/2024,NaN,"Zukowski, Cris",New York,NY,10128,unemployed,unemployed,NaN,NaN,NaN,NaN,30.0,30.0
2144,3179,"Stringer, Scott M",9/29/2024,NaN,"Zurkow, Benjamin",New York,NY,10075,Software Engineer,Copia Automation,43,West 24th Street,New York,NY,500.0,250.0

In [29]:
all_clean = all_clean [['RECIPNAME', 'DATE', 'REFUNDDATE', 'NAME', 'CITY', 'STATE', 'ZIP', 'OCCUPATION', 'EMPNAME', 'EMPSTRNO', 'EMPSTRNAME', 'EMPCITY', 'EMPSTATE', 'AMNT', 'MATCHAMNT']]

In [30]:
all_clean

,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
0,"Adams, Eric L",8/29/2024,NaN,"Abduganiev, Maksudjon",Brooklyn,NY,11229,Dispatcher,Dispatch Limo Seven Transporta,653,E 5th Street,Brooklyn,NY,250.0,250.0
1,"Adams, Eric L",1/8/2025,NaN,"Abrahimi, Farhad",Hicksville,NY,11801,Business,Self-Employed,9,West Marie Street,Hicksville,NY,500.0,0.0
2,"Adams, Eric L",8/11/2024,NaN,"Acevedo, Isaac",Staten Island,NY,10303,Not Employed,Not Employed,NaN,NaN,NaN,NaN,250.0,250.0
3,"Adams, Eric L",8/14/2024,NaN,"Acevedo, Melissa",Staten Island,NY,10303,RN,Richmond Univeristy Medical Ce,355,Bard Ave,Staten Island,NY,250.0,250.0
4,"Adams, Eric L",8/15/2024,NaN,"Achille, Carl",Alden Manor,NY,11003,Sergeant,New York City Police Departmen,8,Catherine Court,Alden Manor,NY,250.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140,"Stringer, Scott M",9/8/2024,NaN,"Zou, Fenger",Flushing,NY,11362,Real Estate Agent,Fengz International INC,34-36,Union Street,Flushing,NY,250.0,250.0
2141,"Stringer, Scott M",11/25/2024,NaN,"Zou, Min Fen",Brooklyn,NY,11214,Floor manager,Min Fen Zou,6812,15th Avenue,Brooklyn,NY,250.0,250.0
2142,"Stringer, Scott M",10/7/2024,NaN,"Zrake, Donald",Levittown,NY,11756,Engineer,Hallam Engineering,97-37,63rd Dr.,Flushing,NY,75.0,0.0
2143,"Stringer, Scott M",12/2/2024,NaN,"Zukowski, Cris",New York,NY,10128,unemployed,unemployed,NaN,NaN,NaN,NaN,30.0,30.0
2144,"Stringer, Scott M",9/29/2024,NaN,"Zurkow, Benjamin",New York,NY,10075,Software Engineer,Copia Automation,43,West 24th Street,New York,NY,500.0,250.0

In [48]:
all_clean = all_clean[all_clean.duplicated(['NAME'], keep=False)]

In [51]:
duplicates = all_clean.groupby("NAME")["RECIPNAME"].apply(list)

In [52]:
duplicates

NAME
Abarbanel, Aliza                        [Mamdani, Zohran K, Myrie, Zellnor]
Abate, Liam               [Lander, Brad, Myrie, Zellnor, Stringer, Scott M]
Aca, Ricardo                            [Mamdani, Zohran K, Ramos, Jessica]
Acevedo, Jose                           [Mamdani, Zohran K, Myrie, Zellnor]
Acton-Bond, Brandon                       [Lander, Brad, Mamdani, Zohran K]
                                                ...
Zeno, Mark                                   [Lander, Brad, Myrie, Zellnor]
Zimmerman, Sandy                             [Lander, Brad, Myrie, Zellnor]
Zulack, Mary                                 [Lander, Brad, Myrie, Zellnor]
danon, kenan                            [Mamdani, Zohran K, Myrie, Zellnor]
van der Meulen, Pamela                    [Lander, Brad, Stringer, Scott M]
Name: RECIPNAME, Length: 635, dtype: object