In [8]:
import pandas as pd

In [9]:
mamdani = pd.read_csv('../data/CFB_mamdani.csv')

In [4]:
mamdani = mamdani[['RECIPNAME', 'DATE', 'REFUNDDATE', 'NAME', 'CITY', 'STATE', 'ZIP', 'OCCUPATION', 'EMPNAME', 'EMPSTRNO', 'EMPSTRNAME', 'EMPCITY', 'EMPSTATE', 'AMNT', 'MATCHAMNT']]

In [5]:
mamdani[mamdani.duplicated(['NAME'], keep=False)]

,RECIPNAME,DATE,REFUNDDATE,NAME,CITY,STATE,ZIP,OCCUPATION,EMPNAME,EMPSTRNO,EMPSTRNAME,EMPCITY,EMPSTATE,AMNT,MATCHAMNT
7,"Mamdani, Zohran K",10/23/2024,NaN,"Abbot, Thomas",Brooklyn,NY,11225,Public Sector,NYS HCR,641,Lexington Avenue,New York,NY,100.0,100.0
8,"Mamdani, Zohran K",1/11/2025,NaN,"Abbot, Thomas",Brooklyn,NY,11225,Public Sector,NYS HCR,641,Lexington Avenue,New York,NY,100.0,100.0
10,"Mamdani, Zohran K",11/21/2024,NaN,"Abdelfatah, Mona",Brooklyn,NY,11209,Engineer,OSE,22,Reade Street,New York,NY,100.0,50.0
11,"Mamdani, Zohran K",12/17/2024,NaN,"Abdelfatah, Mona",Brooklyn,NY,11209,Engineer,OSE,22,Reade Street,New York,NY,100.0,100.0
12,"Mamdani, Zohran K",1/11/2025,NaN,"Abdelfatah, Mona",Brooklyn,NY,11209,Engineer,OSE,22,Reade Street,New York,NY,100.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8260,"Mamdani, Zohran K",10/24/2024,NaN,"Zucker, Alex",Brooklyn,NY,11229,Translator,Self-Employed,2171,Bragg Street,Brooklyn,NY,25.0,25.0
8261,"Mamdani, Zohran K",12/18/2024,NaN,"Zucker, Alex",Brooklyn,NY,11229,Translator,Self-Employed,2171,Bragg Street,Brooklyn,NY,10.0,10.0
8264,"Mamdani, Zohran K",10/23/2024,NaN,"Zwick, Winnie",Brooklyn,NY,11216,Administrative Assistant,Foundation for a Just Society,23,West 20th Street,New York,NY,25.0,25.0
8265,"Mamdani, Zohran K",12/4/2024,NaN,"Zwick, Winnie",Brooklyn,NY,11216,Administrative Assistant,Foundation for a Just Society,23,West 20th Street,New York,NY,200.0,200.0
8266,"Mamdani, Zohran K",11/30/2024,NaN,"Zwick, Winnie",Brooklyn,NY,11216,Administrative Assistant,Foundation for a Just Society,23,West 20th Street,New York,NY,25.0,25.0

In [6]:
mamdani_clean = mamdani.drop_duplicates(subset="NAME")

In [7]:
mamdani_clean.to_csv('../output/mamdani_clean.csv')